services:
  app:
    build: .
    ports:
      - "3000:3000"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge