services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - REDIS_URL=redis://redis:6379

  insurance:
    build: app/api/widgets/insurance/
    ports:
      - "8080:8080"
    networks:
      - app_network

  internet:
    build: app/api/widgets/internet/
    ports:
      - "8081:8081"
    networks:
      - app_network

  media:
    build: app/api/widgets/media-service/
    ports:
      - "8082:8082"
    networks:
      - app_network



  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge